const data = [
    {
      "id": 1,
      "company": "Photosnap",
      "logo": "./images/photosnap.svg",
      "featured": false,
      "position": "Facebook Media Buyer",
      "category": "Marketing",
      "role": "Frontend",
      "level": "Senior",
      "postedAt": "08/15/2022",
      "contract": "Full Time",
      "location": "USA",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["HTML", "CSS", "JavaScript"],
      "tools": ["GA", "Hubspot"]
    },
    {
      "id": 2,
      "company": "Manage",
      "logo": "./images/manage.svg",
      "featured": false,
      "position": "Customer Serice REp",
      "category": "Customer Service",
      "role": "Fullstack",
      "level": "Midweight",
      "postedAt": "08/16/2022",
      "contract": "Part Time",
      "location": "Australia",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["Python"],
      "tools": ["Amplitude"]
    },
    {
      "id": 3,
      "company": "Account",
      "logo": "./images/account.svg",
      "featured": false,
      "position": "UGC Graphic Designer",
      "category": "Creative",
      "role": "Frontend",
      "level": "Junior",
      "postedAt": "08/17/2022",
      "contract": "Part Time",
      "location": "Europe",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["JavaScript"],
      "tools": ["React", "Sass"]
    },
    {
      "id": 4,
      "company": "MyHome",
      "logo": "./images/myhome.svg",
      "featured": false,
      "position": "Email Marketer",
      "category": "Marketing",
      "role": "Frontend",
      "level": "Junior",
      "postedAt": "08/18/2022",
      "contract": "Contract",
      "location": "USA",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["CSS", "JavaScript"],
      "tools": []
    },
    {
      "id": 5,
      "company": "Loop Studios",
      "logo": "./images/loop-studios.svg",
      "featured": false,
      "position": "Software Engineer",
      "category": "Web Development",
      "role": "Fullstack",
      "level": "Midweight",
      "postedAt": "08/19/2022",
      "contract": "Full Time",
      "location": "Asia",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["JavaScript"],
      "tools": ["Ruby", "Sass"]
    },
    {
      "id": 6,
      "company": "FaceIt",
      "logo": "./images/faceit.svg",
      "featured": false,
      "position": "Recruiter",
      "category": "Product",
      "role": "Backend",
      "level": "Junior",
      "postedAt": "08/20/2022",
      "contract": "Full Time",
      "location": "UK",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["Ruby"],
      "tools": ["RoR"]
    },
    {
      "id": 7,
      "company": "Shortly",
      "logo": "./images/shortly.svg",
      "featured": false,
      "position": "Junior Developer",
      "category": "Customer Service",
      "role": "Frontend",
      "level": "Junior",
      "postedAt": "08/21/2022",
      "contract": "Full Time",
      "location": "Europe",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["HTML", "JavaScript"],
      "tools": ["Sass"]
    },
    {
      "id": 8,
      "company": "Insure",
      "logo": "./images/insure.svg",
      "featured": false,
      "position": "Junior Frontend Developer",
      "category": "Customer Service",
      "role": "Frontend",
      "level": "Junior",
      "postedAt": "08/22/2022",
      "contract": "Remote",
      "location": "USA",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["JavaScript"],
      "tools": ["Vue", "Sass"]
    },
    {
      "id": 9,
      "company": "Eyecam Co.",
      "logo": "./images/eyecam-co.svg",
      "featured": false,
      "position": "Full Stack Engineer",
      "category": "Customer Service",
      "level": "Midweight",
      "postedAt": "08/23/2022",
      "contract": "Full Time",
      "location": "Remote",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["JavaScript", "Python"],
      "tools": ["Django"]
    },
    {
      "id": 10,
      "company": "The Air Filter Company",
      "logo": "./images/the-air-filter-company.svg",
      "featured": false,
      "position": "Front-end Dev",
      "category": "People & HR",
      "role": "Frontend",
      "level": "Junior",
      "postedAt": "08/24/2022",
      "contract": "Part Time",
      "location": "Worldwide",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["JavaScript"],
      "tools": ["React", "Sass"]
    }, 
    {
      "id": 11,
      "company": "The Air Filter Company",
      "logo": "./images/the-air-filter-company.svg",
      "featured": false,
      "position": "Salesman",
      "category": "Sales",
      "role": "Frontend",
      "level": "Junior",
      "postedAt": "08/25/2022",
      "contract": "Part Time",
      "location": "Worldwide",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["JavaScript"],
      "tools": ["React", "Sass"]
    },
    {
      "id": 12,
      "company": "Eyecam Co.",
      "logo": "./images/eyecam-co.svg",
      "featured": false,
      "position": "Logistics Man",
      "category": "Biz Ops",
      "level": "Midweight",
      "postedAt": "08/26/2022",
      "contract": "Full Time",
      "location": "Worldwide",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["JavaScript", "Python"],
      "tools": ["Django"]
    },
    {
      "id": 13,
      "company": "Eyecam Co.",
      "logo": "./images/eyecam-co.svg",
      "featured": true,
      "position": "Shipping Guy",
      "category": "Biz Ops",
      "level": "Midweight",
      "postedAt": "08/27/2022",
      "contract": "Full Time",
      "location": "Worldwide",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["JavaScript", "Python"],
      "tools": ["Django"]
    },
    {
      "id": 14,
      "company": "The Air Filter Company",
      "logo": "./images/the-air-filter-company.svg",
      "featured": true,
      "position": "Last is new First",
      "category": "Finance",
      "role": "Frontend",
      "level": "Junior",
      "postedAt": "08/28/2022",
      "contract": "Part Time",
      "location": "Worldwide",
      "whoweare": " We are SOCi, the largest localized-marketing platform globally. We are looking to add a Full Stack Software Engineer to our team and help innovate our expanding group of products. You will have full ownership of a product together with your team. We are a mob programming environment which means we collaborate in real time to create solutions together. SOCi is on the Forbes 2021 list of America’s Best Startup Employers and we would love for you to be a part of our team.",
      "description": "This position is fully remote and our teams are distributed across four continents. You'll be expected to have 6 hours of overlap with your team within the 6:00 AM to 2:00 PM PST time zone, but that can vary by team and location. For instance, some teams may start an hour or two earlier and some teams may start an hour or two later. Taking meaningful breaks is important for engineers to stay sharp and productive throughout the day. You will be collaborating with other engineers by doing Mob programming in real-time over Zoom as part of several sessions throughout the day. A Product Team consists of 2 mobs (each mob consists of 3 engineers), a Tech Lead, an Engineering Manager (EM), a UX designer, and a Product Manager (PM). As a member of an Empowered Product Team, you will be able to work with your assigned teams to research and understand customer problems as part of their jobs. Then work together to build product solutions that address them. We are an engineering company and we leverage technology to solve customer problems.",
      "joblink": "https://www.linkedin.com/jobs/view/3189974133/",
      "skills": ["JavaScript"],
      "tools": ["React", "Sass"]
    }
  ]
  
export default data;